export const Colors = {
  primary: '#16B357',
  primaryLight: '#4CD47F',
  primaryDark: '#0E7A3A',
  background: '#FFFFFF',
  backgroundBeige: '#F2F0DC',
  backgroundLight: '#F0FAF4',
  card: '#FFFFFF',
  text: '#16B357',
  textDark: '#1A1A1A',
  textSecondary: '#555555',
  textLight: '#FFFFFF',
  placeholder: '#AAAAAA',
  border: '#E0E0E0',
  danger: '#D32F2F',
};
