spring.application.name=ecoflow

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EcoFlow;encrypt=true;trustServerCertificate=true
spring.datasource.username=EcoFlow_SQLLogin_1
spring.datasource.password=4obqp2gbcy
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JWT
jwt.secret=ecoflow-tcc-2026-chave-secreta-super-segura-minimo-256bits
jwt.expiration=86400000
